# Generated by Django 5.0.7 on 2025-07-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blog_section_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/gallerie/image'),
        ),
    ]
