# Generated by Django 5.0.7 on 2025-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_blog_status_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Edition', 'Edition'), ('Recent', 'Recent'), ('Trending', 'Trending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/gallerie/'),
        ),
    ]
