# Generated by Django 5.0.7 on 2025-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Trending', 'Trending'), ('Popular', 'Popular'), ('Edition', 'Edition'), ('Prodserv', 'Prodserv'), ('Prodserv1', 'Prodserv1')], max_length=100),
        ),
    ]
