# Generated by Django 5.0.7 on 2025-09-30 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact_date_alter_blog_section_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='objet',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Prodserv', 'Prodserv'), ('Prodserv1', 'Prodserv1'), ('Recent', 'Recent'), ('Edition', 'Edition'), ('Popular', 'Popular'), ('Trending', 'Trending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(max_length=16),
        ),
    ]
