# Generated by Django 5.0.7 on 2025-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contact_objet_alter_blog_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Prodserv', 'Prodserv'), ('Edition', 'Edition'), ('Prodserv1', 'Prodserv1'), ('Trending', 'Trending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], default=0, max_length=1),
        ),
    ]
