# Generated by Django 5.0.7 on 2025-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_description_contact_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='media/Images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Prodserv1', 'Prodserv1'), ('Prodserv', 'Prodserv'), ('Recent', 'Recent'), ('Edition', 'Edition'), ('Trending', 'Trending'), ('Popular', 'Popular')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default=0, max_length=1),
        ),
    ]
