# Generated by Django 5.0.7 on 2025-10-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_blog_img_alter_blog_section_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Prodserv1', 'Prodserv1'), ('Edition', 'Edition'), ('Prodserv', 'Prodserv'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Popular', 'Popular')], max_length=100),
        ),
    ]
